version: "2"

linters:
  disable:
    - errcheck
  enable:
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude:
    # Allow WriteString(fmt.Sprintf) pattern in output formatting
    - "QF1012"
    # Tagged switch suggestions are style preferences
    - "QF1003"
    # Empty branch checks in test files are fine (testing error paths)
    - "SA9003"
    # Append result not used in test is fine
    - "SA4010"
    # Deprecated filepath.HasPrefix is OK for /Applications check
    - "SA1019.*filepath\\.HasPrefix"
    # Unused mock functions in tests are fine
    - "func mock.* is unused"

run:
  timeout: 5m
  tests: true
