version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: brewprune
    main: ./cmd/brewprune
    binary: brewprune
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: brewprune
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat:'
      order: 0
    - title: Bug Fixes
      regexp: '^fix:'
      order: 1
    - title: Others
      order: 999

release:
  draft: false
  prerelease: auto

brews:
  - name: brewprune
    repository:
      owner: blackwell-systems
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/blackwell-systems/brewprune
    description: "Smart Homebrew package cleanup with usage tracking and confidence-scored removal"
    license: MIT
    test: |
      system "#{bin}/brewprune", "--version"
    install: |
      bin.install "brewprune"
